name: "Test Generate UT Automation from JIRA Story"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Validate branch name
        id: validate-branch
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          JIRA_KEY="${{ vars.JIRA_PROJECT_KEY }}"

          if [[ -z "$BRANCH_NAME" ]]; then
              echo "⚠️  Warning: Unable to determine branch name. Skipping validation."
              exit 0
          fi

          if [[ -z "$JIRA_KEY" ]]; then
              echo "⚠️  Warning: JIRA_PROJECT_KEY not set. Skipping branch validation."
              exit 0
          fi

          # Convert to lowercase for case-insensitive comparison
          BRANCH_NAME_LOWER=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]')
          JIRA_KEY_LOWER=$(echo "$JIRA_KEY" | tr '[:upper:]' '[:lower:]')

          if [[ ! "$BRANCH_NAME_LOWER" =~ ^$JIRA_KEY_LOWER ]]; then
              echo "❌ Error: Branch name must start with '$JIRA_KEY' (case-insensitive)"
              echo "Current branch: $BRANCH_NAME"
              echo "Expected format: $JIRA_KEY-XXX-description"
              exit 1
          fi

          echo "✅ Branch name validation passed: $BRANCH_NAME"

      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Build
        run: |
          bash setup.sh

      - name: Run OpenRouterAI Test Quality Checker
        id: run-check-quality-of-unit-testcases-openrouterai
        uses: sourcefuse/check-quality-of-unit-testcases@V1.1.0
        with:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_UT || '' }}
          AWS_REGION: ${{ vars.AWS_REGION_UT || '' }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY_UT || '' }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD || '' }}
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME || '' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_EMAIL: ${{ vars.JIRA_EMAIL }}
          JIRA_PROJECT_KEY: ${{ vars.JIRA_PROJECT_KEY }}
          JIRA_URL: ${{ vars.JIRA_URL }}
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
          OPEN_ROUTER_MODEL: ${{ vars.OPEN_ROUTER_MODEL }}
          PROJECT_DOCUMENT_PATH: ${{ vars.PROJECT_DOCUMENT_PATH || '' }}
          S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME_UT || '' }}
          USE_FOR: ${{ vars.USE_FOR || '' }}
          JIRA_URL_OUTPUT: ${{vars.JIRA_URL_OUTPUT}}
          JIRA_EMAIL_OUTPUT: ${{vars.JIRA_EMAIL_OUTPUT}}
          JIRA_API_TOKEN_OUTPUT: ${{secrets.JIRA_API_TOKEN_OUTPUT}}
          JIRA_SPACE_KEY_OUTPUT: ${{vars.JIRA_SPACE_KEY_OUTPUT}}